Description: "Role that Cloud9 instance will assume to create infrastructure in spoke account (qs-1tggro3ok)"
Parameters:
  CentralAccount:
    Type: String
Resources:
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TerraformSpokeRole
      Path: /
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${CentralAccount}:role/CentralCloud9Role
            Action:
              - 'sts:AssumeRole'
      Policies:
        - 
         PolicyName: "root"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: ["ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:UpdateSecurityGroupRuleDescriptionsEgress",
                "ec2:CreateVpc",
                "ec2:ModifySecurityGroupRules",
                "ec2:Describe*",
                "ec2:UpdateSecurityGroupRuleDescriptionsIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateSecurityGroup",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:DeleteSecurityGroup",
                "ec2:DeleteVpc","ec2:CreateTags","ec2:DeleteTags"]
                Resource: "*"

Outputs:
  SpokeRole: 
    Value: !GetAtt iamRole.Arn
